---
title: Something About Warm Beverages
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: Coffee, tea, and other warm bevvies
author: Naomi
baseurl: /
url: https://somethingaboutwarmbeverages.com
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
- jekyll-feed
- jekyll-paginate
